### ISSUE TITLE
Plugin not connecting to VPN

### ISSUE THREAD

**Issue by rpr13** [bkohler616/TunnelDeck#4]
I added VPN connections in desktop mode, but when using it in plugin it doesn't work.  
It ticks as ON, but connection to VPN is not established, even if its is ON.  
After going backward and againg to plugin, VPN connection is OFF.

On desktop mode VPN mode works fine.

**Comment by bkohler616** [comment]
Hey there @rpr13 !
What version of the plugin are you using? If you're using the default store version, can you swap to the testing version for me and see what type of response data you get back? On the newer version there is a "Network Info" block. After flipping a connection it will refresh. I may also need some information in the "Additional Network Info" block as well.

Thanks!

**Comment by rpr13** [comment]
I am using testing version.

Data in `NETWORK INFO` and `ADDITIONAL NETWORK INFO` is same even after "connected" to VPN

```
NETWORK INFO
Priotitized Network Interface
wlan0

Prioritized Interface LAN IP
192.168.0.7

Can reach gateway
Yes

Can reac steampowered.com
Yes


ADDITIONAL NETWORK INFO
Pinging steampowered.com succeded in 20.061 ms

Pinging 192.168.0.1 in 4.987 ms

DEVICE: wlan0

TYPE: wifi

STATE: 100 (connected)

REASON: 0 (No reason given)

IP4-CONN: 4 (full)

IP6-CONN: 3 (limited)

IP-IFACE: wlan0

CONNECTION: --REDACTED--

METERED: no (guessed)

SPEED: 650 Mb/s

IP4.ADDRESS[1]: 192.168.0.7/24

IP4.GATEWAY: 192.168.0.1

IP4.DNS[1]: --REDACTED--

IP4.DNS[2]: --REDACTED--
```

![IMG_20241022_215039](https://github.com/user-attachments/assets/39edf9d6-e249-41a1-beea-780b0c75fc1b)

**Comment by bkohler616** [comment]
Alrighty, that's pretty strange... Then I can only assume that the VPN is failing to activate...

When you go into desktop mode and you turn on the VPN are you able to reach out to the internet? If so, mind sending me pictures?

If you would prefer this be in private chat (and for speed) would you mind messaging me on Discord? I am available on the Steam Deck Homebrew discord; you can use this thread to contact me:
https://discord.com/channels/960281551428522045/1019739119871590470/threads/1039938126468108310

Here's the invite link if you're not in there!
https://deckbrew.xyz/discord

**Comment by bkohler616** [comment]
We connected in a private chat on discord.

The reason for the error was because the VPN had a password that was encrypted only for the desktop user. We went into the desktop mode, went to configure network connections, then to the VPN and set the password to be `Store password for all users (not encrypted)`.

Once this setting was saved, @rpr13 could use his VPN in the TunnelDeck.

**Comment by rpr13** [comment]
Yup. Sorry. I was sure that I made everything from docs. But I wasn't.  
My bad.
